// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_feeds_and_users.sql

package database

import (
	"context"
)

const getFeedsAndUsers = `-- name: GetFeedsAndUsers :many
SELECT f.name, f.url, u.name FROM feeds f
JOIN users u on f.user_id = u.id
`

type GetFeedsAndUsersRow struct {
	Name   string
	Url    string
	Name_2 string
}

func (q *Queries) GetFeedsAndUsers(ctx context.Context) ([]GetFeedsAndUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsAndUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsAndUsersRow
	for rows.Next() {
		var i GetFeedsAndUsersRow
		if err := rows.Scan(&i.Name, &i.Url, &i.Name_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
