// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mark_feed_fetched.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const markedFeedFetched = `-- name: MarkedFeedFetched :one
update feeds
    set updated_at = current_timestamp, last_fetched_at = current_timestamp
    where id = $1

returning id, created_at, updated_at, name, url, user_id, last_fetched_at
`

func (q *Queries) MarkedFeedFetched(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, markedFeedFetched, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
