// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: remove_feed_follow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const removeFeedFollow = `-- name: RemoveFeedFollow :exec
delete from feed_follows where user_id = $1 and feed_id = $2
`

type RemoveFeedFollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) RemoveFeedFollow(ctx context.Context, arg RemoveFeedFollowParams) error {
	_, err := q.db.ExecContext(ctx, removeFeedFollow, arg.UserID, arg.FeedID)
	return err
}
